<?php
    $codigos = array('EF-6ºA-M-11775-21','EF-7ºA-M-11775-21','EF-8ºA-M-11775-21','EM-1ªA-M-11775-21','EM-1ªB-M-11775-21','EM-1ªC-M-11775-21',
    'EM-2ªA-M-11775-21','EM-3ªA-M-11775-21','QCEPP01I','QEI17N','AICQ01T-1','AICQI33T-2','AICQI34N-2','AIEM26M-2','AIEX03T-1','AIIRRC12T-2',
    'AIME01M-01','AIME02T-01','AIPA49T-2','AIPA50N-2','AIPA52T-1','AIPA53N-1','AIPPI04T-1','HT-MEC-001-N-01','HT-MET-001-T-01','HT-MET-002-N-01',
    'TAI22N-2','TAIEAD03I-3','TAIEAD04I-1','TAIEAD05I-1','TE01I-1','TM46N-2','TM46N-3','TMMECA24N-3','TMMECA24N-4','TMMM40N-4','AIAL01T-1',
    'AICQ01T-2','AICQ02T-1','AIEX03T-2','AIFEDCRP01M-1','AIMAELE01T-1','AIME01M-02','AIME02T-02','AIPA52T-2','AIPA53N-2','AIPA56T-1','AIPA57N-1',
    'AIRRC01M-1','AITA05M-1','AITA06T-1','HT-ELM-001-N-01','Funcionarios');

    $turmas = array('6º ANO A','7º ANO A', '8º ANO A', '1º ANO A', '1º ANO B', '1º ANO C', '2º ANO A','3º ANO A','QUAL. CONT. PROG. PRODUÇÃO',
    'QUAL. ELETRICISTA INDUSTRIAL','AP. CONTROLE QUALIDADE','APR. CONTROLE QUALIDADE','APR. CONTROLE QUALIDADE','APR. ELETROMECÂNICA',
    'APR. ELETROMECÂNICA (ROBÓTICA)','APR. REDES COMPUTADORES','APR. MANUT. ELETROMECÂNICA','APR. MANUT. ELETROMECÂNICA','APR. PROCESSOS ADMINISTRATIVOS',
    'APR. PROCESSOS ADMINISTRATIVOS','APR. PROCESSOS ADMINISTRATIVOS','APR. PROCESSOS ADMINISTRATIVOS','APR. PROC. PRODUÇÃO INDUSTRIAL',
    'TÉCNICO EM MECÂNICA', 'TÉCNICO EM MECATRÔNICA', 'TÉCNICO EM MECATRÔNICA','TÉCNICO EM AUTOMAÇÃO', 'TÉCNICO AUTOMAÇÃO INDUSTRIAL', 
    'TÉCNICO AUTOMAÇÃO INDUSTRIAL','TÉCNICO AUTOMAÇÃO INDUSTRIAL','TÉCNICO EM ELETROTÉCNICA','TÉCNICO EM MECÂNICA','TÉCNICO EM MECÂNICA',
    'TÉCNICO EM MECATRÔNICA','TÉCNICO EM MECATRÔNICA','TÉCNICO EM MECÂNICA','APR. AUX. DE LOGÍSTICA','AP. CONTROLE QUALIDADE', 'AP. CONTROLE QUALIDADE',
    'APR. ELETROMECÂNICA (ROBÓTICA)','APR. EM FERRAMENTARIA','APR. MANUT. ELETROMECÂNICA','APR. MANUT. ELETROMECÂNICA','APR. MANUT. ELETROMECÂNICA',
    'APR. PROCESSOS ADMINISTRATIVOS','APR. PROCESSOS ADMINISTRATIVOS','APR. PROCESSOS ADMINISTRATIVOS','APR. PROCESSOS ADMINISTRATIVOS','APR. REDES DE COMPUTADORES',
    'APR. TAPECEIRO DE AUTOS','APR. TAPECEIRO DE AUTOS','TÉCNICO EM ELETROMECÂNICA','TÉCNICO EM ELETRÔNICA');
    
    $busca = array_search('EM-1ªA-M-11775-21',$codigos);
    echo $turmas[$busca];
?>